title: TheMoneyMakers.se 
description: > # this means to ignore newlines until "baseurl:"
  We help you who are new in Sweden make the most of your money and start investing.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: The Money Makers .se # add your name
author-img: mm-logo-old-tighter.png # add your photo
about-author: We help you who are new in Sweden make the most of your money and start investing. Follow us on instagram by pressing the icon below # Sidebar description
# add description
social-instagram: themoneymakers.se
social-email: moneymakersnordic@gmail.com # add your Email address
social-github: #moneymakersnordic # add your Github handle
social-linkedin: #
social-facebook: #
social-twitter: #

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
